version: '3.8'

services:
  backend:
    build: .
    container_name: projet
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload

# docker-compose up --build
# docker-compose down --rmi all --volumes