services:
  backend:
    build: .
    container_name: backend
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - intra_docs_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      timeout: 5s
      interval: 10s
      retries: 3
    restart: always

  db:
    image: postgres:18
    container_name: db
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - intra_docs_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      timeout: 5s
      interval: 10s
      retries: 3
    restart: always
  
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6380:6379"
    networks:
      - intra_docs_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always

volumes:
  postgres_data:

networks:
  intra_docs_network:
    name: intra_docs_network
    driver: bridge

# docker compose up --build
# docker compose down --rmi all --volumes