services:
  backend:
    build: .
    container_name: backend
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - intra_docs_network

  db:
    image: postgres:18
    container_name: db
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - intra_docs_network

volumes:
  postgres_data:

networks:
  intra_docs_network:
    name: intra_docs_network
    driver: bridge

# docker compose up --build
# docker compose down --rmi all --volumes